// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Kerekes_Denisa_SADE.Data;

namespace Project_Kerekes_Denisa_SADE.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project_Kerekes_Denisa_SADE.Models.Chocolate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Flavour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.ToTable("Chocolate");
                });

            modelBuilder.Entity("Project_Kerekes_Denisa_SADE.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Project_Kerekes_Denisa_SADE.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChocolateID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderID");

                    b.HasIndex("ChocolateID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Project_Kerekes_Denisa_SADE.Models.SuppliedChocolate", b =>
                {
                    b.Property<int>("ChocolateID")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("ChocolateID", "SupplierID");

                    b.HasIndex("SupplierID");

                    b.ToTable("SuppliedChocolate");
                });

            modelBuilder.Entity("Project_Kerekes_Denisa_SADE.Models.Supplier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("Project_Kerekes_Denisa_SADE.Models.Order", b =>
                {
                    b.HasOne("Project_Kerekes_Denisa_SADE.Models.Chocolate", "Chocolate")
                        .WithMany("Orders")
                        .HasForeignKey("ChocolateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_Kerekes_Denisa_SADE.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chocolate");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Project_Kerekes_Denisa_SADE.Models.SuppliedChocolate", b =>
                {
                    b.HasOne("Project_Kerekes_Denisa_SADE.Models.Chocolate", "Chocolate")
                        .WithMany("SuppliedChocolates")
                        .HasForeignKey("ChocolateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_Kerekes_Denisa_SADE.Models.Supplier", "Supplier")
                        .WithMany("SuppliedChocolates")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chocolate");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Project_Kerekes_Denisa_SADE.Models.Chocolate", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("SuppliedChocolates");
                });

            modelBuilder.Entity("Project_Kerekes_Denisa_SADE.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Project_Kerekes_Denisa_SADE.Models.Supplier", b =>
                {
                    b.Navigation("SuppliedChocolates");
                });
#pragma warning restore 612, 618
        }
    }
}
